name: Deploy to VPS

on:
  push:
    branches:
      - quitmood

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          echo "🔐 Connecting to VPS and deploying..."

          ssh -o StrictHostKeyChecking=no root@$VPS_IP << 'EOF'
            set -e  # Dừng script nếu gặp lỗi

            echo "📁 Chuyển đến thư mục dự án"
            cd /var/www/quitmood-nextjs

            echo "🔁 Git pull"
            git pull origin quitmood

            echo "🛑 Dừng và xoá container cũ (nếu có)"
            docker stop quitmood-fe-container || true
            docker rm quitmood-fe-container || true

            echo "🧹 Xoá image cũ"
            docker rmi quitmood-fe || true

            echo "🛠️ Build image mới"
            docker build -t quitmood-fe .

            echo "🚀 Chạy container mới"
            docker run -d --name quitmood-fe-container -p 4016:4010 quitmood-fe
          EOF
